package rules;

import com.example.riskcontrol.model.LoginEvent
import com.example.riskcontrol.service.BlackListService
import com.example.riskcontrol.model.BlackList
import com.example.riskcontrol.service.DimensionService

global BlackListService blackListService
global DimensionService dimensionService

rule "997_all_blackip"
    salience 997
    lock-on-active true
    when
          event:LoginEvent()
    then
        if(blackListService.contain(BlackList.EnumDimension.IP,BlackList.EnumType.WHITE,event.getOperateIp())){
            dimensionService.insertEvent(event);
            delete(event);
        }

        if(blackListService.contain(BlackList.EnumDimension.IP,BlackList.EnumType.BLACK,event.getOperateIp())){
            event.setScore(100);
            dimensionService.insertEvent(event);
            dimensionService.insertRiskEvent(event,"黑名单ip");
            delete(event);
        }
end